### PR TITLE
MON-3841: Bump prometheus-promu to v0.16

### PR DESCRIPTION
**Pull request by danielmellado**
This commit bumps promu version to v0.16 tag from upstream.

Signed-off-by: Daniel Mellado <dmellado@redhat.com>

### CODE REVIEW

**Comment by jan--f** [comment]
hmm shouldn't this include the added upstream commits? Is this the result of `git merge v0.16.0`?

**Comment by danielmellado** [comment]
Yes, I added `--squash`to that to avoid so much noise over here but let me put it there as well.

**Comment by jan--f** [comment]
Got it. Lets not squash...upstream history can be interesting in bug finding.

**Comment by danielmellado** [comment]
There it goes, unsquashed version ;)

**Comment by jan--f** [comment]
hmm this still loks different from the upstream history. There are no merge commits? Also we'll need the vendored go deps. Like in https://github.com/openshift/prometheus-promu/pull/2.

**Comment by danielmellado** [comment]
it was all amended but I split them out to be explicit, for the record, this is the outcome of
```
git merge tags/v0.16.0
go mod vendor
git add vendor/ -f
```

Hope this is clear now!

**Comment by jan--f** [comment]
> it was all amended but I split them out to be explicit, for the record, this is the outcome of
> 
> ```
> git merge tags/v0.16.0
> go mod vendor
> git add vendor/ -f
> ```
> 
> Hope this is clear now!

There is still some history altering happening. If I merge the tag my history looks different.
```
commit d4dc1c56d581ecfabe17bc508978672ef44b536b (HEAD -> bump-0.16, tag: v0.16.0)
Merge: 8ca87dc 36b1874
Author: Ben Kochie <superq@gmail.com>
Date:   Wed Apr 3 12:16:46 2024 +0200

    Merge pull request #297 from prometheus/superq/v0.16.0

    Release v0.16.0

commit 36b1874b73015223f942a3d71d534aa2ab8b6430
Author: SuperQ <superq@gmail.com>
Date:   Tue Apr 2 14:57:19 2024 +0200

    Release v0.16.0

    * [FEATURE] Do not discover user/host for reproducible builds #267
    * [BUGFIX] Fix example/prometheus build error #274

    Signed-off-by: SuperQ <superq@gmail.com>

commit 8ca87dc45eb8790da1b73f29212e765949cf00cc
Merge: 4f6560e a949505
Author: Ben Kochie <superq@gmail.com>
Date:   Tue Apr 2 14:52:47 2024 +0200

    Merge pull request #293 from prometheus/dependabot/go_modules/github.com/prometheus/common-0.51.1

    Bump github.com/prometheus/common from 0.47.0 to 0.51.1

commit a949505fc567d8aef429ba4702f5d2dd2ac42754
Author: SuperQ <superq@gmail.com>
Date:   Tue Apr 2 14:44:04 2024 +0200

**Comment by danielmellado** [comment]
hmm same as in my history here...
```
commit 4ea6ca3 (HEAD -> bump_promu_to_0_16)
Author: Daniel Mellado <dmellado@redhat.com>
Date:   Wed Apr 24 16:14:46 2024 +0200

    Add go mod vendor
    
    Signed-off-by: Daniel Mellado <dmellado@redhat.com>

commit b555d74
Merge: 6838099 d4dc1c5
Author: Daniel Mellado <dmellado@redhat.com>
Date:   Wed Apr 24 16:12:13 2024 +0200

    Merge tag 'tags/v0.16.0' into bump_promu_to_0_16
    
    v0.16.0

commit d4dc1c5 (tag: v0.16.0)
Merge: 8ca87dc 36b1874
Author: Ben Kochie <superq@gmail.com>
Date:   Wed Apr 3 12:16:46 2024 +0200

    Merge pull request #297 from prometheus/superq/v0.16.0
    
    Release v0.16.0

commit 36b1874
Author: SuperQ <superq@gmail.com>
Date:   Tue Apr 2 14:57:19 2024 +0200

    Release v0.16.0
    
    * [FEATURE] Do not discover user/host for reproducible builds #267
    * [BUGFIX] Fix example/prometheus build error #274
    
    Signed-off-by: SuperQ <superq@gmail.com>

commit 8ca87dc
Merge: 4f6560e a949505
Author: Ben Kochie <superq@gmail.com>
Date:   Tue Apr 2 14:52:47 2024 +0200

    Merge pull request #293 from prometheus/dependabot/go_modules/github.com/prometheus/common-0.51.1
    
    Bump github.com/prometheus/common from 0.47.0 to 0.51.1
```

I use a wrapper that might be doing some odd with this, let me take a quick look

**Comment by danielmellado** [comment]
IMHO should be ok now, please have a look, thanks!

**Comment by jan--f** [comment]
TY!
/lgtm

**Pull request merged**
